### PR TITLE
Added Tepper to README.md

### PR DESCRIPTION
**Pull request by mirman-aitepper2016**
Subscrieb for more minecrft vids i do playtrhu i appreciate the liks and subs thx

### CODE REVIEW

**Comment by mirman-mtaggart** [comment]
Add all members of the class in a list under an h2 called "Team".

**Comment by mirman-mirovenger2016** [comment]
:^)

**Comment by mirman-mirovenger2016** [comment]
:^)

**Comment by mirman-mtaggart** [comment]
Use Markdown, not HTML for `.md` files.

**Pull request closed without merging**
